# Customise this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.60.1"

default_platform :ios
# FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD = "mkvw-hvcz-gsko-vnnq"

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    # carthage
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Car-Connect") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Upload Metadata to App Store"
  lane :deliver do
    deliver(force: true)
  end

  desc "Increment the build number and Commit"
  lane :increment do

    # Bump build number
    increment_build_number

    # Commit and push to remote
    commit_version_bump(
      message: 'Build number bump by fastlane - 'ios increment' lane',
      force: true
    )

    push_to_git_remote(
      remote: "origin",         # optional, default: "origin"
      local_branch: "development",  # optional, aliased by "branch", default: "master"
      remote_branch: "development", # optional, default is set to local_branch
      tags: false     # optional, default: true
    )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    increment_build_number
    match(type: "appstore")
    gym(scheme: "Car-Connect") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  desc "Deploy Metadata and screenshots from the App Store"
  lane :download_metadata do
    download_screenshots
    download_metadata
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
